name: Changeset existence
on:
    pull_request:
        branches: [main]
        types: [labeled, opened, synchronize, reopened]
    workflow_dispatch:
jobs:
    changeset:
        name: Check for changeset existence
        runs-on: ubuntu-latest
        if: ${{ !contains(github.event.pull_request.labels.*.name, 'chore') }}

        steps:
            - name: Checkout
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0

            - name: Use Node 20
              uses: actions/setup-node@v3
              with:
                  node-version: 20

            - name: Install pnpm 8.x.x
              uses: pnpm/action-setup@v2.2.4
              with:
                  version: 8.x.x

            - name: Install pnpm dependencies (with cache)
              uses: covbot/pnpm-install-with-cache@v1

            - name: Danger
              run: pnpm danger ci
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
