name: 'coverage'
on:
    pull_request:
        paths-ignore:
            - 'docs/**'
            - 'example/**'
        branches:
            - main
jobs:
    coverage:
        runs-on: ubuntu-latest
        env:
            CI_JOB_NUMBER: 1
        steps:
            - uses: actions/checkout@v1
            - uses: artiomtr/jest-coverage-report-action@v2
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  test-script: npm run test
                  threshold: 90
