name: Release

on:
    push:
        branches:
            - main
    workflow_dispatch:

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
    release:
        name: Release
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0

            - name: Use Node 20
              uses: actions/setup-node@v3
              with:
                  node-version: 20

            - name: Install pnpm 8.x.x
              uses: pnpm/action-setup@v2.2.4
              with:
                  version: 8.x.x

            - name: Install pnpm dependencies (with cache)
              uses: covbot/pnpm-install-with-cache@v1

            - name: Creating .npmrc
              run: |
                  cat << EOF > "$HOME/.npmrc"
                    //registry.npmjs.org/:_authToken=$NPM_TOKEN
                  EOF
              env:
                  NPM_TOKEN: ${{ secrets.NPM_BOT_TOKEN }}

            - name: Create Release Pull Request or Publish to npm
              uses: changesets/action@v1
              with:
                  version: pnpm bump
                  publish: pnpm release
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
